apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  DISCORD_CLIENT_ID: "${DISCORD_CLIENT_ID}"
  DISCORD_CLIENT_SECRET: "${DISCORD_CLIENT_SECRET}"
  JWT_SECRET: "${JWT_SECRET}"
  DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
  MONGO_URI: "${MONGO_URI}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: default
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
  MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
  MONGODB_URI: "${MONGODB_URI}"
